TOP_WIDTH = 1100
TOP_DEPTH = 600
TOP_THICKNESS = 12

MACHINE_WIDTH = 600
MACHINE_DEPTH = 475
MACHINE_HEIGHT = 850
MACHINE_DOOR_BULGE = 60
MACHINE_LEFT_MARGIN = 50
MACHINE_RIGHT_MARGIN = 50
PIPE_GAP = 100
MACHINE_FRONT_OFFSET = TOP_DEPTH - PIPE_GAP - MACHINE_DEPTH

BASIN_CERAMIC_DIAMETER = 390
BASIN_INNER_DIAMETER = 330
BASIN_CUTOUT_DIAMETER = 350
BASIN_CENTER_X = 865
BASIN_CENTER_Y = 300

MIXER_HOLE_DIAMETER = 35
MIXER_BODY_DIAMETER = 55
MIXER_SPOUT_REACH = 130
MIXER_CENTER_X = 1000
MIXER_CENTER_Y = 490

BRACKET_WIDTH = 30
BRACKET_DEPTH = 403
BRACKET_TOTAL_HEIGHT = 303
BRACKET_ARM_HEIGHT = 30
BRACKET_CENTERS = [60, 655, 1070]

MACHINE_CLEARANCE = 10
ARM_UNDERSIDE = MACHINE_HEIGHT + MACHINE_CLEARANCE
TOP_UNDERSIDE = ARM_UNDERSIDE + BRACKET_ARM_HEIGHT
FINISHED_HEIGHT = TOP_UNDERSIDE + TOP_THICKNESS
BRACKET_BOTTOM = TOP_UNDERSIDE - BRACKET_TOTAL_HEIGHT

FRONT_OVERHANG = TOP_DEPTH - BRACKET_DEPTH
MAX_OVERHANG = 200
MAX_SUPPORT_SPACING = 600
